---
title: "HW09: Analyzing Hadestown"
author: "Julia Du"
date: "`r lubridate::today()`"
output: 
  github_document:
    toc: true
---

## Load necessary libraries

```{r, message = FALSE}
library(tidyverse)
#library(geniusr)
library(genius) #even easier than geniusr
library(scales)

library(tidytext)
library(reshape2)
library(wordcloud)
library(widyr)
library(ggraph)
library(igraph)

library(textrecipes)
library(topicmodels)

library(viridis)
library(ggtext)
theme_set(theme_minimal())
set.seed(123)

```

## get Hadestown lyrics

used super easy package `genius` & didn't even have to use an API

```{r}
hadestown <- genius_album(artist = "Anais Mitchell", album = "Hadestown (Original Broadway Cast Recording)")

phantom <- genius_album(artist = "Andrew Lloyd Webber", album = "The Phantom of the Opera (Original London Cast Recording)")

lesmis <- genius_album(artist = "Les Miserables Original Broadway Cast", album = "Les Miserables (1987 Original Broadway Cast)")
```

## sentiment analysis

```{r}
string_hades <- hadestown %>%  
  pull(track_title) %>%
  str_remove(pattern = " by.*")

hadestown_tidy <- hadestown %>%
  bind_cols(string_hades) %>%
  select(-track_title) %>%
  rename(track_title = ...5) %>%
  mutate(track_title = as_factor(track_title)) %>%
# now tokenize
  unnest_tokens(output = word, input = lyric) %>%
  anti_join(stop_words)

hadestown_afinn <- hadestown_tidy %>%
  inner_join(get_sentiments(lexicon = "afinn")) %>%
  mutate(cum_sent = cumsum(value), id = row_number())

hadestown_afinn %>%
  group_by(track_title) %>%
  summarize(sent = mean(value)) %>%
  ggplot(mapping = aes(x = fct_rev(track_title), y = sent, fill = sent)) +
  geom_col() +
  scale_fill_viridis_c() +
  coord_flip() +
  labs(
    title = "Positive/negative sentiment in *Hadestown*",
    subtitle = "By song",
    x = NULL,
    y = "Average sentiment",
    fill = "Average\nsentiment",
    caption = "Source: Genius"
  ) +
  theme(plot.title = element_markdown(),
        legend.position = "none")
```

## adjust figure size!

```{r}
ggplot(data = hadestown_afinn, mapping = aes(x = id, y = cum_sent)) +
  geom_line() +
  scale_x_reverse(breaks = hadestown_afinn %>%
                    group_by(track_n) %>%
                    filter(id == min(id)) %>%
                    pull(id),
                  labels = hadestown_afinn %>%
                    group_by(track_n) %>%
                    filter(id == min(id)) %>%
                    pull(track_title)) +
  labs(
    title = "Positive/negative sentiment in *Hadestown*",
    x = NULL,
    y = "Cumulative sentiment",
    caption = "Source: Genius"
  ) +
  # transpose to be able to fit song titles on the graph
  coord_flip() +
  theme(panel.grid.minor.y = element_blank(),
        plot.title = element_markdown())
```

```{r}
custom_hades <- c("la", "gonna")

custom_hades_stop <- bind_rows(tibble(word = custom_hades, lexicon = c("custom")), stop_words)


hades_cors <- hadestown_tidy %>%
  anti_join(custom_hades_stop) %>%
  group_by(word) %>%
  filter(n() >= 20) %>%
  pairwise_cor(item = word, feature = track_n, sort = TRUE)
# looking at the common pairs of words co-appearing w/in each article (as defined by recent_order)

hades_cors %>%
  filter(item1 %in% c("hell", "love", "song", "livin", "gotta", "wait")) %>%
  group_by(item1) %>%
  slice_head(n = 5) %>%
  ungroup() %>%
  mutate(item2 = reorder(item2, correlation)) %>%
  ggplot(mapping = aes(x = item2, y = correlation)) +
  geom_col() +
  facet_wrap(~ item1, scales = "free") +
  coord_flip()

hades_cors %>%
  filter(correlation > .35) %>%
  graph_from_data_frame() %>%
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_alpha = correlation), show.legend = FALSE) +
  geom_node_point(color = "orangered3", size = 5) +
  geom_node_text(aes(label = name), repel = TRUE) +
  ggtitle("Word pairs with at least a correlation of .35 appearing in the same song")
  theme_void()


```

## Comparing word frequencies

https://www.tidytextmining.com/tidytext.html

```{r}
string_phan <- phantom %>%  
  pull(track_title) %>%
  str_remove(pattern = " by.*")

phantom_tidy <- phantom %>%
  bind_cols(string_phan) %>%
  select(-track_title) %>%
  rename(track_title = ...5) %>%
  mutate(track_title = as_factor(track_title)) %>%
# now tokenize
  unnest_tokens(output = word, input = lyric) %>%
  anti_join(stop_words)

string_lesmis <- lesmis %>%
  pull(track_title) %>%
  str_remove(pattern = " by.*")

lesmis_tidy <- lesmis %>%
  bind_cols(string_lesmis) %>%
  select(-track_title) %>%
  rename(track_title = ...5) %>%
  mutate(track_title = as_factor(track_title)) %>%
# now tokenize
  unnest_tokens(output = word, input = lyric) %>%
  anti_join(stop_words)

# compare words in Hadestown to Phantom of the Opera
frequency <- bind_rows(mutate(hadestown_tidy, musical = "Hadestown"),
                       mutate(phantom_tidy, musical = "Phantom of the Opera"),
                       mutate(lesmis_tidy, musical = "Les Miserables")) %>% 
  #mutate(word = str_extract(word, "[a-z']+")) %>%
  count(musical, word) %>%
  group_by(musical) %>%
  mutate(proportion = n / sum(n)) %>% 
  select(-n) %>%
  pivot_wider(names_from = musical, values_from = proportion) %>%
  pivot_longer(c("Phantom of the Opera", "Les Miserables"), names_to = "musical", values_to = "proportion")


# plot

frequency %>%
  ggplot(mapping = aes(x = proportion, y = `Hadestown`, 
                       color = abs(`Hadestown` - proportion))) +
  geom_abline(color = "gray40", lty = 2) +
  geom_jitter(alpha = 0.1, size = 2.5, width = 0.3, height = 0.3) +
  geom_text(aes(label = word), check_overlap = TRUE, vjust = 1.5) +
  scale_x_log10(labels = percent) +
  scale_y_log10(labels = percent) +
  scale_color_gradient(limits = c(0, 0.001), 
                       low = "darkolivegreen4", high = "gold3") +
  facet_wrap(~ musical) +
  theme(legend.position="none") +
  labs(y = "Hadestown", x = NULL)
```    



## Session info

```{r, echo = TRUE}
devtools::session_info()
```
